name: Build, Test, and Push Staging Image to DockerHub

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Git SHA
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      # other build steps...

  deploy-infra:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Recreate TAG for this job
      - name: Set Git SHA
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan \
          -var-file=staging.tfvars \
          -var="docker_image=${{ secrets.DOCKERHUB_USERNAME }}/credpal-app-staging:${{ env.TAG }}"
